services:
  hackerrank-sandbox:
    container_name: hackerrank-sandbox
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Evita conflictos con node_modules en el host
    
